### ISSUE TITLE
About the method update_node_metrics (core.py)

### ISSUE THREAD

**Issue by davidperezabreu** [acsicuib/YAFS#16]
Hello,
I’m implementing an alternative placement mechanism in YAFS and I realized that after running some test simulations the result file for the execution of the tasks was empty, meanwhile the results file for the network transmissions was ok. After taking a look at the YAFS core files, I realized something in the file core.py (i.e.; lines # 436 and #437).

```
# att_node = self.topology.get_nodes_att()[id_node] # WARNING DEPRECATED from V1.0
att_node = self.topology.G.nodes[id_node]
```

When I was trying to reach the node attributes using the active instruction (i.e., line #437) I got nothing but using the commented one (i.e., line #436) I got the value that I was looking for. Considering the comments on the code the instruction in line #436 is deprecated and replaced for the instruction in line #437; nevertheless, the behavior that I was getting is different.
Can somebody help me with this issue? Maybe I’m doing something wrong?

I’m attaching a screenshot of the values of evaluating the instructions during a debugging session (https://imgur.com/a/DxG2j9e)

Cheers,

David

**Comment by wisaaco** [comment]
Hi David,

In the previous version, the attributes of a node were stored in two places: a specific dictionary and in the dictionary that manages the Networkx (Nx) library. In order to keep coherent both structures, it was decided to use only the Nx implementation.

Thus, the deprecated function used the internal dictionary and the new one obtains the values from the Graph. (https://networkx.github.io/documentation/stable/reference/generated/networkx.classes.function.set_node_attributes.html <https://networkx.github.io/documentation/stable/reference/generated/networkx.classes.function.set_node_attributes.html>)


I have to check and test the load functions and also the generation functions of topologies. All attribute assignments have to be done directly with the functions of Nx. 

Thank you! As soon as I can, I review all the functions involved in the topology class.

Best,
Isaac

**Comment by wisaaco** [comment]
I've fixed this issue in all examples.
