### ISSUE TITLE
Regarding implementation of batch placement algorithms

### ISSUE THREAD

**Issue by Ktechkun** [acsicuib/YAFS#29]
How can i make processes wait in Selection algorithms in get_path function, i tried doing sim.env.timeout
I want to run placement algorithm after every time slice, which maps tasks in queue.

**Comment by wisaaco** [comment]
The function get_path is triggered when a new message requires a network/service routing. It's complicated to set an interval control in this function. 

The best way to implement that behaviour is to create a periodic process. This process can have multiples parameters;  one of them is the instance of the network/service routing (the class where the _get_path_ function is implemented). Plus, this periodic process can change the internal variables or structures of the network/service routing.

An example of this behaviour can be implemented with the following parts of code:
- In the main file, you define both controls: 

```
selectorPath = DeviceSpeedAwareRouting()

activation_dist = deterministic_distribution(200, name="Deterministic")
network_control = YourACTION(path_csv_files=path_csv_files,app_number=len(dataApp))
s.deploy_monitor("Control-Operator", network_control, activation_dist,**{"sim": s, "routing": selectorPath, "path":experiment_path})
```

- in your YourACTION class:
```
def __call__(self, sim, routing, path):
    if some_criteria:
         routing.change_policy = True
````

- and finally, in your routing class (aka _DeviceSpeedAwareRouting_):
```
def __init__(self):
        self.change_policy = False

def get_path(self, sim, app_name, message, topology_src, alloc_DES, alloc_module, traffic, from_des):
     if self.change_policy:
      #do a different pathing selection
    else:
      # bla bla 
```

**Comment by Ktechkun** [comment]
Thank you for the quick reply, this is helpful in another way. But I wanted to, implement the batch placement of tasks for this, I can create a queue to store all incoming messages/requests. This batch scheduler find the mapping between devices and tasks in the queue. Messages calling get_path need to be waiting till path is recieved 
![Untitled Diagram](https://user-images.githubusercontent.com/18036434/69986193-e3243280-1562-11ea-97e9-3229e8784012.png)

**Comment by wisaaco** [comment]
You're right, my first idea doesn't model your architecture.  
I come up a couple of ideas, but all of them have to modify functions of YAFS core since It is not possible to stop/pause the DES process when calls the _get_path_ function.

Let's do it! My proposal is the following:

1. It is necessary to introduce a buffer for each module or app. This depends on your model.
In function core.py: _def deploy_app(self, app, placement, population, selector)_ create a global array of **simpy.Stores** for modules/apps. (https://simpy.readthedocs.io/en/latest/topical_guides/resources.html#stores) 

2. Before sending a message, the DES process should add it in the corresponding buffer (store.put) and the consumer entity (your _batchmapper_) will compute the path and it will give permissions to continue the process.
You should add the message before _self.__send_message(name_app, msg, idDES, self.SOURCE_METRIC)_ function is called. For example:

````
 def __add_source_population(self, idDES, name_app, message, distribution):
  ...
      msg.id = self.__getIDMessage()
      msg.original_DES_src = idDES
      # HERE (put message and wait response/path)
      self.__send_message(name_app, msg, idDES, self.SOURCE_METRIC)
...
````
In that point, the message can have a new attribute with the computed path. So, you need to comment the line _paths,DES_dst = self.selector_path[app_name].get_path(...)_ in __send_message function.  Another option is to return the path and enter it as a parameter. As you wish.

3.  You can implement the batchmapper DES process like "a normal" monitor with access to the simulator vars (and the new simpy.stores). It means, it is like the previous post: "YourACTION class"

**Comment by Ktechkun** [comment]
Thank you, your proposal is working.  I used two stores one for request queue and other for returning path.
