### ISSUE TITLE
Install on Mac

### ISSUE THREAD

**Issue by wei12f8158** [acsicuib/YAFS#37]
Hi there,

I use PyCharm and i wanna import YAFS to my MacBook.
But i totally don't know how to do it.
Could you give some suggestion? 

thx~

**Comment by wisaaco** [comment]
Hello! 
The best way is to put the YAFS-core folder in your project, like other own libraries. Take a look at this project: [https://github.com/acsicuib/MARIO/tree/MarioII](https://github.com/acsicuib/MARIO/tree/MarioII) As you can see, there is a folder YAFS with the essentials. The other py files import them.
You're welcome!

**Comment by wei12f8158** [comment]
@wisaaco  
I meet an issue when i want to put YAFS-core in my project.
Could you give some help?

thanks~ :)

<img width="1280" alt="截圖 2021-01-24 21 02 55" src="https://user-images.githubusercontent.com/49111480/105631204-43bdaf80-5e88-11eb-8b67-d839c9d0d2ac.png">
<img width="534" alt="截圖 2021-01-24 21 05 09" src="https://user-images.githubusercontent.com/49111480/105631207-46b8a000-5e88-11eb-9cad-841f278d55ff.png">

**Comment by wei12f8158** [comment]
I have an issue that when i run main1.py, it showing that an error from simpy.core.
But i already installed simpy in python interpreter.
Did you have any suggestion?

Gracias!

<img width="1280" alt="截圖 2021-01-24 21 42 01" src="https://user-images.githubusercontent.com/49111480/105634235-07924b00-5e98-11eb-8958-7db486127ea1.png">

**Comment by wisaaco** [comment]
Hello!
Try to clone the project instead to install with pip. Pip contains an initial yafs version... It is my old pending task: remove yafs'pip version :(

So, first, do a "git clone" and then move the folder YAFS (the core)  into your project. In your project, you can tag the folder as a "source root".
![Captura de pantalla 2021-01-25 a las 8 37 15](https://user-images.githubusercontent.com/3286592/105674931-8fa04100-5ee8-11eb-87fb-d72245e6a8a0.png)

Second, In order to install dependencies, you can use the requirements file. https://github.com/acsicuib/YAFS/blob/YAFS3/requirements.txt Copy and paste the libs in your req. file.

And finally, in your "run" configuration select the automatic load of folders into the Pythonpath
![Captura de pantalla 2021-01-25 a las 8 39 12](https://user-images.githubusercontent.com/3286592/105675204-076e6b80-5ee9-11eb-9438-90b47c314308.png)

Good luck! 运气！

**Comment by wei12f8158** [comment]
Hi~ 

I did git clone, Tag folder as source root and installed requirement.txt
But i got an error when i running.
ImportError: cannot import name 'deterministicDistribution' from 'yafs.distribution' 

Do you have suggestions?? 
Muchas gracias :)

<img width="1280" alt="截圖 2021-01-29 18 14 30" src="https://user-images.githubusercontent.com/49111480/106263457-5b69af00-625f-11eb-9d05-318e2434f948.png">
<img width="1280" alt="截圖 2021-01-29 18 23 55" src="https://user-images.githubusercontent.com/49111480/106263470-5e649f80-625f-11eb-9296-1967a2d717f9.png">

**Comment by wisaaco** [comment]
Hello,

There are some small changes in the versions between the core and the tutorials (some of them come from older version). Sorry for that.
The function is called: “deterministic_distribution”

Are you running: "https://github.com/acsicuib/YAFS/blob/YAFS3/src/tutorial_scenarios/basicExample/main.py”? <https://github.com/acsicuib/YAFS/blob/YAFS3/src/tutorial_scenarios/basicExample/main.py%E2%80%9D?>
Take care to clone the new version of YAFS3, because you are using pyhon3.9. In the YAFS3 all examples of “tutorial_scenarios” folders should be work fine.

The old examples (“examples” folder) are not updated and they can generate some problems in YAFS3.

Best

**Comment by wei12f8158** [comment]
Hello,

It worked ! thanks a lot ; )

Muchas gracias~

<img width="1280" alt="截圖 2021-01-29 22 09 40" src="https://user-images.githubusercontent.com/49111480/106284958-d42c3380-627e-11eb-8bce-8a030e29d7ff.png">

**Comment by wisaaco** [comment]
super!!!! 
Please don’t hesitate to contact me if you need more help!
