### ISSUE TITLE
Time loops in results

### ISSUE THREAD

**Issue by sanket099** [acsicuib/YAFS#62]
Hi @wisaaco , what is the use and meaning of # time_loops = [["M.A", "M.B"]] in analyising results in main1.py in src/examples/Tutorials

**Comment by wisaaco** [comment]
Hi @sanket099 , time_loops was a variable to calculate metrics considering a sequence of messages. Thus, one can calculate the response time of a single message (MA) or the sum of messages caused (MA->MB). 
I did not devote efforts to improve the functionalities to analyze the simulation traces (*stats* functions) because these traces depend on the nature of the scenario so it is very difficult to implement a large casuistry. I recommend analysing the traces according to your problem/interest with Panda library.
One naive example of this is this https://github.com/acsicuib/MARIO/blob/MarioII/multi-agent-policies/plot_responseTime.py file, that computes the response time of each application and generates a plot.
Best
