### ISSUE TITLE
orchestration 

### ISSUE THREAD

**Issue by Raghad1997** [acsicuib/YAFS#9]
Hello, 

As  I meantion before that, I use the YAFS simulation for my graduation project, so I have a question
it is possible in the simulation to select a node to be an orchestrator ( what I mean when a user sends a request to the fog node this fog node ( fog  orchestrator) it will orchestrate and select the nodes based on the user's request and the available resources to build a specific computational network??

**Comment by wisaaco** [comment]
Hello, 
I think that it is possible. There are different alternatives to do it.

**One possible solution**
In all the scenarios, you need to define the routing algorithm. So, you can extend this method for your purposes. Look a basic example in examples/Tutorial/simpleSelection.py or more complex case in examples/DynamicFailureOnNodes/selection_multipleDeploys.py

The method has this signature and it called from the _core_ when a new message has to be addressed 
```
def get_path(self, sim, app_name, message, topology_src, alloc_DES, alloc_module, traffic):
```
where you can get, the node which sends the message _topology_src_ and all possibles deployed modules that can manage this message:
```
DES_dst = alloc_module[app_name][message.dst]  
```
In this point, you can do whatever you want: create new nodes (sim.topology), deploy more modules, change the application in the user, etc.

With this idea in mind, the development process could be:

1.  Define an application where users need to connect with an "orchestrator" entity
2. Orchestrator entities receive the user's requests and perform your actions
3. When a user requests again the service of an application, the routing can:
3.1. can be routed through the orchestrator entity and be cached the final destination.
3.2 can be routed through the orchestrator entity and it computes new actions.
3.3. can go directly to the application module without going through the orchestrator since the _application type_ has been modified in step 2.
...

Best

**Comment by Raghad1997** [comment]
example in examples/Tutorial/simpleSelection.py the shortest path based on what  ?

**Comment by wisaaco** [comment]
The network topology is based on graphs through the Networkx library.  In this case, we use the nx.shortest_path function which computes the shortest path based on the number of nodes (hop count)
[https://networkx.github.io/documentation/networkx-2.2/reference/algorithms/shortest_paths.html](https://networkx.github.io/documentation/networkx-2.2/reference/algorithms/shortest_paths.html)

**Comment by Narmeen-Darawshe** [comment]
@wisaaco 
Hello
I want to ask how can I use the cost (or other node attributes) instead of hop count to find the shortest path?

**Comment by wisaaco** [comment]
Hello Narmeen,

You can use specific attributes of the network to compute the path. Thus, using the same function of this thread, you can introduce that attribute in the _weight_ parameter. 

```
shortest_path(G, source=None, target=None, weight=None, method='dijkstra')
```

Here you have an example with networkx library: [https://stackoverflow.com/questions/14353743/how-to-find-shortest-path-in-a-weighted-graph-using-networkx]( https://stackoverflow.com/questions/14353743/how-to-find-shortest-path-in-a-weighted-graph-using-networkx)

**How you can introduce your custom attributes in the YAFS topology?**
The most efficient way is using networkx functions. For example, example/DynamicFailureOnNodes/main.py, line 69:
```
 centrality = nx.betweenness_centrality(t.G) #return a dictionary (key:id_node)
 nx.set_node_attributes(t.G, name="centrality", values=centrality)
```
Note: the current version in the github of the JSON-based definition of the scenario does not support the load of custom attributtes.

**Comment by Raghad1997** [comment]
@wisaaco 
Good evening,

I want to ask  for a scenario which acts as follow : 
1. user sent an " interest" request for the fog orchestrator.
2. the fog broadcast the request " here we will have a **physical topology**,  so we need to construct the 
**the logical topology** that based on :
-  Cost (Network metric) and the weight of the node ( computation power and battery .. etc).
3. After the logical topology, we apply the Minimum Spanning tree **MPT** to remove the loops.
4. After that, we apply the breath first to select the node that has big computation power and battery 
5. After that, we need to apply the shortest path to reach the selected node.

My question can we apply this scenario in YAFS simulation ?? If it is possible how we can apply it ??

I will be Grateful, 
Regards
Raghad

**Comment by wisaaco** [comment]
I close this issue since you open another with the same topics.
Thanks
Isaac
